language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
  - jruby-19mode
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
before_install:
 - gem update --remote bundler
 - git clone --depth 1 git://github.com/bbatsov/rubocop.git vendor/rubocop
script:
  - bundle exec rake
